### ISSUE TITLE
Send to all affiliates

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#122]
@reasonat @navotb 
 האם הקביעה הזו לא נכונה בקביעת affiliates?
Select if this content can be shown to all affiliates. This setting will override the options below, but you must still select a domain that "owns" this content.
אם נוד סומן כשייך לשני הדומיינים, אבל סומן כpublish רק בדומיין אחד, האם הסימון כsend to all affiliates לא קובע שהנוד יהיה מוצג בשני הדומיינים?

מה שאני רואה כרגע שאם לדוגמא איש סומן כsend to all affilaites אבל סומן כpublish to jerusalem cinematheque אז לא נמצא אותו בדומיין פסטיבל וההפך. זה עלול ליצור כפילויות מיותרות, אם לא כבר יצר

ואם זה המצב, בואו נקבע ש"איש" מסומן בדיפולט כמוצג בשני הדומיינים

**Comment by JerusalemCinematheque** [comment]
ורק לחדד זה דבר אחד שלא מוצאים נוד בפרונטאנד, אבל המצב עכשיו הוא שגם  אי אפשר למצוא את הנודים במערכת הניהול אם הנוד לא סומן כמוצג בשני הדומיינים

**Comment by JerusalemCinematheque** [comment]
עוד הערה
כשאנחנו יוצרים סרט ורוצים לקשר איש, אז כן אפשר למצוא אותו גם אם הוא רק publish לדומיין אחד
אז נראה שהבעיה נמצאת בחיפוש של מערכת הניהול

**Comment by yakoub** [comment]
please provide example node (moive/ event) and full link of the admin page where you expect it to appear .

**Comment by navotb** [comment]
Check this node:
http://jff.reasonat.com/en/person/1089

Should be apprearing here:
http://jer-cin.org.il/en/admin/persons-manager?language=All&title=&field_person_type_target_id_selective=All&field_cm_person_job_title_value_selective=All&field_cm_person_type_target_id_selective=All&field_hide_search_value=All&tnid=All&items_per_page=25

**Comment by yakoub** [comment]
hi @navotb 

this not a problem but a feature and is caused by function my_utilities_views_pre_view which alex wrote .
when i add "return" to that function then the person appears in search results .

more info for alex @sato2004 :
this person : http://jff.reasonat.com/en/person/1089
appears here : http://jff.reasonat.com/en/admin/persons-manager
but not here : http://jer-cin.org.il/en/admin/persons-manager

i think this can be fixed by either excluding admin view in that function or fixing the query filter so that "send to all affiliates" gets handled correctly .
@sato2004 you should also use hook_views_query_alter and not pre_view

**Comment by yakoub** [comment]
@sato2004 using views_query_alter will show the changes in views admin page "preview" function and that allows future developer to notice the alter work done .

**Comment by yakoub** [comment]
@sato2004 also take into consideration this bug : https://www.drupal.org/node/1276694
i fixed it other project campus@reasonat:~/com.git commit 464eedd6081 file campus_logo.views.inc

**Comment by sato2004** [comment]
fixed

**Comment by reasonat** [comment]
Closing this issue. Reopen if needed.
