### ISSUE TITLE
dev site has problem with path event/%

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#169]
related :  [https://www.wrike.com/open.htm?id=142672742https://www.wrike.com/open.htm?id=142672742](https://www.wrike.com/open.htm?id=142672742)

**Comment by yakoub** [comment]
@reasonat there is no problem actually, what happened was event published to domain jff while i was checking it under jer-cin .
this started with admin page : `admin/events-manager` which shows events regardless of current domain .
maybe we need to fix that view so that table display for each event in the table which domain it belongs to .

**Comment by reasonat** [comment]
Sure, admin pages should also take into consideration domain access. 
I think - 
 on Cinema there should be both Festival and Cinema nodes, 
and on Festival only Festival nodes. 
@JerusalemCinematheque ?

**Comment by yakoub** [comment]
i think the optimal way is all content shows on admin page but each row link should lead to the correct domain and table new column should show each content domain name .

**Comment by reasonat** [comment]
This is a related issue - https://github.com/Reasonat1/Cinema/issues/192 
Yet this one deals with another aspect. 
@yakoub Please explain again

**Comment by yakoub** [comment]
@reasonat explain what ?

**Comment by reasonat** [comment]
This comment isn't clear 
https://github.com/Reasonat1/Cinema/issues/169#issuecomment-307835857

**Comment by yakoub** [comment]
correction : "and new table column should show each content domain name"

so again, the link in each row should already have the correct domain when generated and not relative path to current domain .
and we need to add new column to the table that says each content which domain it belongs to .

**Comment by reasonat** [comment]
You mean, if lets say, I want to review movie /love and it's display both on jer-cin & jff, then on: 
jer-cin it will be jer-cin.org.il/movie/love
jff it will be jff.org.il/love

Which I think is the opposite of what you mean.

**Comment by navotb** [comment]
BTW, Films that are assigned only to jff are still available through
jer-cin, but without synopsis. The desired result is either (1) there is
not such film on jer-cin or to redirect to jff.

**Comment by yakoub** [comment]
the problem is content admin page like 'admin/events-manager' will show links to content that is not accessible because of domain restriction .

suggested solution is for example movie 'love' that belongs to jff then the table should show full path link regardless of current domain .
meaning even under jer-cin it will still show path jff.org.il/movie/love .
if otherwise movie belongs to both jff and jer-cin then it should remain relative path .
@reasonat @JerusalemCinematheque

**Comment by navotb** [comment]
If I understand correctly, this is like "Redirect", no?

**Comment by yakoub** [comment]
a redirect means you open link under one address jff.org.il/movie/love and it redirects to another address like jer-cin.org.il/movie/love
but what i suggest has no redirection because the link is already generated with correct full address .

**Comment by navotb** [comment]
As long as the functionality is the same: meaning if a node is enabled only
on one domain, then when clicking on it you will be directed to the right
domain and will not be getting a crippled page on the wrong domain - it is
ok.
By the way - if I will be entering (typing) the url address with the wrong
domain - what will happen?

**Comment by yakoub** [comment]
this not related to site wide behavior and policy at all .
this is only about the admin content table .
we can also simply add column to the table about which domains it belong to and this way the content administrator will understand what happened if the page opens up in "error not found" .

**Comment by navotb** [comment]
Oh. I thought you were talking about the public side of the website, since
my last remark was about getting half baked pages when entering from the
"not makred" domain.
We already have the domain column.

But in terms of functionality, we wish to prevent either "page not found"
or "half baked page".

**Comment by JerusalemCinematheque** [comment]
so if editor wants to access content belonging to the other domain what happens?
for intstance
if i am in jercin domain and search for film or event 1945 which belongs to jff domain
then there is no issue with editing the node, even if it belongs to other domain?

**Comment by yakoub** [comment]
i think if currently you don't have problems with content admin pages, then this issue should be closed .

as for discussing public side of the website, it should be in different issue .
