### ISSUE TITLE
anayltics historical data

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#206]
jff.org.il previously had independent analytics property .
but new configuration reports both domains to same property .
the problem is past jff data does not show up in new property .

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

related documentation : https://support.google.com/analytics/answer/6370521?hl=en

**Comment by navotb** [comment]
I don't understand what it means, but fact is our account do not have data
since we switched to new site.

**Comment by yakoub** [comment]
@navotb 
באימייל ששלחתה לי לא אמרתה שהבעיה שהחשבון לא מכיל נתונים אלא הבעיה אחרת , ציטוט
"הבעיה היא שהחשבון שהצבעתי עליו הוא החשבון עם הנתונים ההיסטורים ואילו החשבון שאליו נאספים הנתונים עכשיו לא כולל את הנתונים האלו"

כתבתה "החשבון שאליו נאספים נתונים", כלומר הוא כן מכיל נתונים ולא לא מכיל נתונים בכלל .

תחליט בבקשה מה הגדרת הבעיה בדיוק לפני שאני ממשיך לעבוד

ממה שאני רואה הנתונים משני הדומיינים מגיעים לחשבון ואין בעיה שחשבון לא מכיל מידע בכלל
https://analytics.google.com/analytics/web/#report/defaultid/a7605141w14530570p152302598/

**Comment by yakoub** [comment]
@navotb both domains data are captured into your analytics account property UA-7605141-1

what i understood is that you need data from jff that have accumulated through the years .

but if your problem is that you simply do not know how to access the current data for domain jff,
then it is waste of time for me to find solution for merging or migrating the old property data .

**Comment by navotb** [comment]
My problem is that current data is sent to view 152302598 from account
UA-7605141-1

But our historic data is on UA-7605141-2 view 32530427, and I wish to keep
gathering data to this account and view.

**Comment by yakoub** [comment]
@navotb alright then what i wrote in issue main description is correct .

you request that we report data to the old jff property, but
what i want to try instead is to migrate data from old jff property to the new property we currently report to and not change the way we report data .
because reporting to different properties from same website is not recommended setup for analytics .

**Comment by navotb** [comment]
Ok. So give it a short try, and if it doesnot work we will work the old way.

**Comment by yakoub** [comment]
@navotb 
there is no standard way to migrate data between properties .

to add the second property id like you request is also complicated .
the reason it is complicated is we have single website with same database while your previous website i assume were separated so reporting to two separate properties was more straight forward .

the drupal analytics module allows working with only one property and to add additional property will need custom coding and altering default behaviour, i estimate it will take 4 hours .

why do you need this historical data ? 
your new data is reported correctly for both domains without problems .
are you still interested in investing effort to report specifically to the old property ?
